### ISSUE TITLE
%u": unexpected EOF while looking for matching `"'

### ISSUE THREAD

**Issue by mattydebie** [linhx/firefox-profiles-selector#1]
Hello !

I was looking for a program like this to select a profile to open an external link.

I tried pouring this package into an AUR package, because I don't like manually putting files in locations and forgetting about them.

However, I get the following error when trying to open a URL:
```bash
%u": unexpected EOF while looking for matching `"'
```

I have the following files in `/opt/firefox-profiles-selector`:
```bash
/opt/firefox-profiles-selector
├── config.ini
├── config.ini.dist
├── firefox-profiles-selector
└── icon.png
```

#### config.ini
```bash
[setting]
profiles_path = ~/.mozilla/firefox/profiles.ini
exec_path = firefox
```

The desktop file is at `/usr/share/applications/firefox-profiles-selector.desktop`
```bash
[Desktop Entry]
Version=1.0.2
Name=Firefox profiles selector
Comment=Firefox profiles selector
Exec=bash -i -c "/opt/firefox-profiles-selector/firefox-profiles-selector %u"
Terminal=false
Type=Application
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/vnd.mozilla.xul+xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;
Icon=/opt/firefox-profiles-selector/icon.png
```

**Comment by mattydebie** [comment]
Okay was probably a bit too soon to open an issue, when changing the `Exec` line of the desktop file to:
```bash
Exec=/opt/firefox-profiles-selector/firefox-profiles-selector %u
```

.. it works

**Comment by mattydebie** [comment]
Maybe informative: this package is now in the AUR
https://aur.archlinux.org/packages/firefox-profiles-selector

If you want to maintain or co-maintain, let me know

**Comment by linhx** [comment]
hi @mattydebie, please add more information.
Which OS are you using?
I guess it because of the double quote. It should be
```
Exec=bash -i -c '/opt/firefox-profiles-selector/firefox-profiles-selector %u'
```
In Ubuntu, it works fine even with the double quoute.

---

I wonder how your desktop file has the double quote. The install script is using single quote.

**Comment by mattydebie** [comment]
Hey @linhx , I'm using Arch linux.

I'm not using the install.sh, since it is an AUR package, it's not "allowed" to edit the user's home dirs.

The good thing is that it works now, and is installable as a package for arch users. The only thing I really had to change was the Exec line to not invoke bash, but your binary directly
